---
- block:
  - name: "Create {{ macos_home_path }}/.zshrc"
    become: yes
    template:
      src: zsh/.zshrc
      dest: "{{ macos_home_path }}/.zshrc"
      owner: "{{ macos_user }}"

  - name: "Create {{ macos_home_path }}/.gitconfig"
    become: yes
    template:
      src: git/.gitconfig
      dest: "{{ macos_home_path }}/.gitconfig"
      owner: "{{ macos_user }}"

  - name: "Create {{ macos_home_path }}/.config"
    become: yes
    file:
      path: "{{ macos_home_path }}/.config"
      state: directory
      owner: "{{ macos_user }}"

  - name: "Create {{ macos_home_path }}/.config/git"
    become: yes
    file:
      path: "{{ macos_home_path }}/.config/git"
      state: directory
      owner: "{{ macos_user }}"

  - name: "Create {{ macos_home_path }}/.config/git/ignore"
    become: yes
    template:
      src: .config/git/ignore
      dest: "{{ macos_home_path }}/.config/git/ignore"
      owner: "{{ macos_user }}"
