name: CI

on:
  push:
    workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: make ansible/lint

  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - run: make test

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: make ansible/check
