name: macOS

on:
  push:
    workflow_dispatch:

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - run: make ansible/init ansible/lint

  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: init
        run: make init zsh/init ansible/init

      - name: test
        run: |
          source ~/.zshrc
          source ~/.zprofile
          make ansible/test
        shell: zsh {0}

  check:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - run: make ansible/init ansible/check
