name: WSL2

on:
  push:
    workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: make ansible/lint

  # いつかWSL2向けにplaybookを書いたらここでテストを回す

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: make ansible/check
